apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: argocd
  namespace: istio-gateways
spec:
  hosts:
    - "argocd.example.com"
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
      cluster: cluster1
  http:
    - name: root-argocd
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: argocd
              cluster: cluster1
            port:
              number: 80
            kind: EXTERNAL_SERVICE
