apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: gloo-ui
  namespace: istio-gateways
spec:
  hosts:
  - "192.168.106.6.nip.io"
  ports:
  - name: ui
    number: 8090
    protocol: HTTP
  selector: {}